CHANGES.md
README.md
liquidhaskell.cabal
src/Language/Haskell/Liquid/Bare.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Constraint/Types.hs
src/Language/Haskell/Liquid/CoreToLogic.hs
src/Language/Haskell/Liquid/Dictionaries.hs
src/Language/Haskell/Liquid/Errors.hs
src/Language/Haskell/Liquid/GhcMisc.hs
src/Language/Haskell/Liquid/Measure.hs
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/PredType.hs
src/Language/Haskell/Liquid/Types.hs
tests/crash/RClass.hs
tests/neg/LiquidClass.hs
tests/neg/LiquidClass1.hs
tests/neg/StateConstraints0.hs
tests/neg/StateConstraints00.hs
tests/pos/LiquidClass.hs
tests/pos/RelativeComplete.hs
tests/pos/StateConstraints0.hs
tests/pos/StateConstraints00.hs
tests/todo/StateConstraints.hs
tests/todo/fio.hs

See [tests/neg/LiquidClass.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/d32f45167aaa336ff874f622a8993a7e67a51c61/tests/neg/LiquidClass.hs), [tests/pos/LiquidClass.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/d32f45167aaa336ff874f622a8993a7e67a51c61/tests/pos/LiquidClass.hs)
and [tests/neg/StateConstraints00.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/d32f45167aaa336ff874f622a8993a7e67a51c61/tests/neg/StateConstraints00.hs)

Constraints on Class Methods

---

.travis.yml

Sorry, this got left in here from when I was working on #306.

Minor: Remove testing branches from .travis.yml

---

src/Language/Haskell/Liquid/Bare/RTEnv.hs

Remove extra debugging traces

---

tests/icfp15/MiniPosix.hs

At the very bottom of this file is 'createTest,' which depends on an implementation of select/update in fixpoint.

add MiniPosix test

---

.travis.yml
include/CoreToLogic.lg
include/Data/Map.hiddenspec
include/Language/Haskell/Liquid/Prelude.hs
include/Prelude.spec
tests/neg/maps.hs
tests/pos/Product.hs
tests/pos/maps.hs
tests/pos/maps1.hs
tests/test.hs
tests/todo/maps.hs

**Do not merge** until travis says ok!
See 
https://github.com/ucsd-progsys/liquidhaskell/blob/maps/tests/pos/maps.hs
https://github.com/ucsd-progsys/liquidhaskell/blob/maps/tests/pos/maps1.hs
https://github.com/ucsd-progsys/liquidhaskell/blob/maps/tests/neg/maps.hs
also depends on matching PR in liquid-fixpoint https://github.com/ucsd-progsys/liquid-fixpoint/pull/43

Maps: adding support for select/store

---

src/Language/Haskell/Liquid/Bare/Env.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Bare/RefToLogic.hs
src/Language/Haskell/Liquid/Bare/Spec.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/CoreToLogic.hs
src/Language/Haskell/Liquid/Measure.hs
src/Language/Haskell/Liquid/Parse.hs
tests/pos/inline.hs

support for inlining haskell functions to logic

---

src/Language/Haskell/Liquid/Types.hs

Depends on https://github.com/ucsd-progsys/liquid-fixpoint/pull/54

Use the smarter pretty-printer in fixpoint

---

src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Spec.hs
tests/pos/LocalSpec0.hs
tests/pos/LocalSpecImp.hs
tests/todo/MM.hs

Fix name resolution for local specifications in imported modules

---

benchmarks/icfp15/pos/Filter.lhs
benchmarks/icfp15/pos/Overview.lhs
include/Language/Haskell/Liquid/Prelude.hs
liquidhaskell.cabal
src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/Env.hs
src/Language/Haskell/Liquid/Bare/Existential.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Bare/Misc.hs
src/Language/Haskell/Liquid/Bare/OfType.hs
src/Language/Haskell/Liquid/Bare/Resolve.hs
src/Language/Haskell/Liquid/Bare/Spec.hs
src/Language/Haskell/Liquid/Bounds.hs
src/Language/Haskell/Liquid/CoreToLogic.hs
src/Language/Haskell/Liquid/Measure.hs
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/PrettyPrint.hs
src/Language/Haskell/Liquid/Types.hs

See for the new bound syntax [benchmarks/icfp15/pos/Overview.lhs](https://github.com/ucsd-progsys/liquidhaskell/blob/bounds/benchmarks/icfp15/pos/Overview.lhs)

Adding better syntax for bounds

---

scripts/travis

Tiny PR to have Travis test this out before merging.

Fix travis_retry in .travis.yml

---

benchmarks/icfp15/neg/DBMovies.hs
benchmarks/icfp15/pos/DBMovies.hs
benchmarks/icfp15/pos/DBMovies0.hs
include/GHC/CString.spec
src/Language/Haskell/Liquid/Bare/RefToLogic.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/CoreToLogic.hs
src/Language/Haskell/Liquid/Literals.hs
src/Language/Haskell/Liquid/RefType.hs
tests/neg/Strings.hs
tests/pos/AVLRJ.hs
tests/pos/Strings.hs
tests/pos/eqelems.hs
tests/todo/BadError0.hs

strings as sym constants

---

Liquid.hs
Makefile
README.md
src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/DataType.hs
src/Language/Haskell/Liquid/Bare/Env.hs
src/Language/Haskell/Liquid/Bare/Expand.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Bare/OfType.hs
src/Language/Haskell/Liquid/Bare/Plugged.hs
src/Language/Haskell/Liquid/Bare/RTEnv.hs
src/Language/Haskell/Liquid/Bare/Resolve.hs
src/Language/Haskell/Liquid/Bare/Spec.hs
src/Language/Haskell/Liquid/CmdLine.hs
src/Language/Haskell/Liquid/DiffCheck.hs
src/Language/Haskell/Liquid/GhcMisc.hs
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/PredType.hs
src/Language/Haskell/Liquid/RefType.hs
src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/WiredIn.hs
tests/todo/fixme.hs

This causes many changes rippling across liquid-fixpoint (see the `diff` branch there).
@spinda -- should we merge this into `master` **now** rather than later? I fear this will cause you major headaches otherwise?
@nikivazou and @gridaphobe  please advise.
related to: https://github.com/ucsd-progsys/liquid-fixpoint/pull/60

Improvements to `--diff` mode

---

tests/test.hs

For passing arbitrary extra options to LH

Add `--liquid-opts` flag to the testsuite

---

src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/RefType.hs
tests/neg/TerminationNum.hs
tests/neg/TerminationNum0.hs
tests/pos/TerminationNum.hs
tests/pos/TerminationNum0.hs

Termination

---

src/Language/Haskell/Liquid/Parse.hs

This allows for Unicode character and single quotes in datatype name. For example `data Λλ'` is excepted but `data λ'` would not. Should be easy to apply this same definition to variable ids. I'll get on started that once I have a chance to meet with @nikivazou. #273

Data types now take unicode characters and single quotes.

---

benchmarks/icfp15/neg/RIO.hs
benchmarks/icfp15/pos/RIO.hs
benchmarks/icfp15/pos/RIO2.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
tests/todo/kmpMonad.hs

should not create constraints on their abstract refinements
fix for #412

Non fully applied TyCons 

---

liquidhaskell.cabal
src/Language/Haskell/Liquid/Desugar710/Check.hs
src/Language/Haskell/Liquid/Desugar710/Coverage.hs
src/Language/Haskell/Liquid/Desugar710/Desugar.hs
src/Language/Haskell/Liquid/Desugar710/DsArrows.hs
src/Language/Haskell/Liquid/Desugar710/DsBinds.hs
src/Language/Haskell/Liquid/Desugar710/DsCCall.hs
src/Language/Haskell/Liquid/Desugar710/DsExpr.hs
src/Language/Haskell/Liquid/Desugar710/DsExpr.hs-boot
src/Language/Haskell/Liquid/Desugar710/DsForeign.hs
src/Language/Haskell/Liquid/Desugar710/DsGRHSs.hs
src/Language/Haskell/Liquid/Desugar710/DsListComp.hs
src/Language/Haskell/Liquid/Desugar710/DsMeta.hs
src/Language/Haskell/Liquid/Desugar710/DsUtils.hs
src/Language/Haskell/Liquid/Desugar710/HscMain.hs
src/Language/Haskell/Liquid/Desugar710/Match.hs
src/Language/Haskell/Liquid/Desugar710/Match.hs-boot
src/Language/Haskell/Liquid/Desugar710/MatchCon.hs
src/Language/Haskell/Liquid/Desugar710/MatchLit.hs
src/Language/Haskell/Liquid/Desugar710/StaticPtrTable.hs
src/Language/Haskell/Liquid/GhcMisc.hs

@ranjitjhala the diff/patch idea worked quite well, only had a few small things to tweak

patch the 7.10 desugarer because SourceNotes aren't providing enough data

---

src/Language/Haskell/Liquid/CmdLine.hs

Change how configs are merged. Priority is _File > Command Line > Environment_ per today's discussion with @ranjitjhala and @gridaphobe.
Will close issue #431

Merge configs such that File > CmdLine > Env

---

Syntax.md

I added my "function syntax" for specifications that I proposed long ago.
I also put @nikivazou's contributions in a pretty table, as githib's markdown formatter was butchering what she wrote.

My contribution to syntax.md

---

Syntax.md

Clearing pull request backlog by merging all my pull requests into this branch

Pull updates to master into cores

---

src/Language/Haskell/Liquid/CmdLine.hs

Clearing pull request backlog by merging all my pull requests into this branch

Factoring `defaultFoo` functions in CmdLine to fixpoint

---

src/Language/Haskell/Liquid/CmdLine.hs
tests/todo/Append.hs

Check again new fixpoint sort check

set new check again

---

README.md
liquidhaskell.cabal

Added version requirements to all cabal entries

---

src/Language/Haskell/Liquid/Bare/OfType.hs

Expression arguments weren't being resolved before being substituted into aliases. This fixes that.
@nikivazou could you please test this?

Resolve expr args to aliases (fixes #468)

---

scripts/performance/deploy-gipeda.bash
scripts/performance/generate-site.bash

Scripts now perform cabal update as needed.

Perf monitor scripts now do cabal update

---

benchmarks/icfp15/pos/DataBase.hs
tests/pos/LambdaDeBruijn0.hs
tests/pos/RBTree-col-height.hs
tests/pos/RBTree-color.hs
tests/pos/RBTree-height.hs
tests/pos/RBTree.hs

bump fixpoint to grab uniqification of value variables

---

src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Constraint/ToFixpoint.hs

See https://github.com/ucsd-progsys/liquid-fixpoint/pull/161

Ws to hashmap

---

scripts/performance/generate-site.bash
scripts/performance/log2csv.hs

Now handling build failures by emitting an empty log.

Merge latest updates to perf-mon into master

---

src/Language/Haskell/Liquid/Parse.hs
tests/pos/T531.hs

treat _ as lower-case

---

src/Language/Haskell/Liquid/Bare/Axiom.hs
src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/DataType.hs
src/Language/Haskell/Liquid/Bare/Env.hs
src/Language/Haskell/Liquid/Bare/Existential.hs
src/Language/Haskell/Liquid/Bare/Expand.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Lookup.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Bare/Misc.hs
src/Language/Haskell/Liquid/Bare/OfType.hs
src/Language/Haskell/Liquid/Bare/Plugged.hs
src/Language/Haskell/Liquid/Bare/RTEnv.hs
src/Language/Haskell/Liquid/Bare/RefToLogic.hs
src/Language/Haskell/Liquid/Bare/Resolve.hs
src/Language/Haskell/Liquid/Bare/Spec.hs
src/Language/Haskell/Liquid/Bare/SymSort.hs
src/Language/Haskell/Liquid/Types/Errors.hs

Completed `error` and `errorstar` elimination for all of Bare.
Will send PR's for others as I finish them.

L.H.L.Bare.* completed

---

src/Language/Haskell/Liquid/Bare/DataType.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Plugged.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Constraint/Monad.hs
src/Language/Haskell/Liquid/Constraint/Split.hs
src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/Types/Errors.hs
src/Language/Haskell/Liquid/Types/RefType.hs
tests/pos/T598.hs

only rewrite casts that are actually constructing a dictionary

---

README.md
src/Language/Haskell/Liquid/Bare/Axiom.hs
src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Constraint/Qualifier.hs
src/Language/Haskell/Liquid/Constraint/Split.hs
src/Language/Haskell/Liquid/Constraint/Types.hs
src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/Types/Errors.hs
tests/neg/BadHMeas.hs
tests/pos/GoodHMeas.hs

Hmeas error

---

src/Language/Haskell/Liquid/Types/Errors.hs

This fixes the issue where an error occurring before GHC was initialized would produce an unrelated GHC error message.

Don't use unsafeGlobalDynFlags to print SrcSpan

---

README.md

Hackage badges courtesy of [shields.io](https://shields.io).

Add Hackage badges to README

---

src/Language/Haskell/Liquid/GHC/Interface.hs
src/Language/Haskell/Liquid/Liquid.hs
src/Language/Haskell/Liquid/Types/Errors.hs
src/Language/Haskell/Liquid/UX/CmdLine.hs
src/Language/Haskell/Liquid/UX/DiffCheck.hs
tests/neg/test00c.hs

Output Contextual Errors in DiffCheck Mode

---

README.md
src/Language/Haskell/Liquid/Constraint/Generate.hs
tests/test.hs

And changes for adding Kuts to FQ query, and code for --eliminate which is very promising but still blows up now and then...
Matching PR for:
ucsd-progsys/liquid-fixpoint#222

New ordering heuristics

---

src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Bare/Spec.hs
src/Language/Haskell/Liquid/Constraint/Env.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Constraint/Types.hs
src/Language/Haskell/Liquid/Transforms/CoreToLogic.hs
src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/UX/DiffCheck.hs
tests/neg/AutoTerm.hs
tests/neg/AutoTerm1.hs
tests/pos/AVLRJ.hs
tests/pos/AutoTerm.hs
tests/pos/AutoTerm1.hs
tests/pos/GhcListSort.hs
tests/pos/WBL.hs
tests/pos/WBL0.hs

Turn measure post condition into invariants
TODO: check that measure types do not have any pre conditions

Measure invariants

---

tests/strings/pos/StringIndexingStep2.hs

Strings Cond

---

CONTRIBUTING.md
README.md

I also added a small contributing guide as @ranjitjhala suggested in #809.

Fix typos in README and add contributing guide

---

include/Language/Haskell/Liquid/String.hs
tests/strings/pos/StringIndexingStep3.hs
tests/todo/UnfoldDataCons.hs

Cont on proving monoid laws for string matching

Monoid laws

---

docs/blog/2016-09-05-refinement-reflection.lhs
include/Language/Haskell/Liquid/ProofCombinators.hs
src/Language/Haskell/Liquid/Parse.hs
tests/pos/RefinedADTs.hs

Blog post on refinement reflection

Refinement reflection

---

src/Language/Haskell/Liquid/Constraint/ToFixpoint.hs
src/Language/Haskell/Liquid/Liquid.hs

Companion PR to https://github.com/ucsd-progsys/liquid-fixpoint/pull/266

remove fileName from GInfo

---

src/Language/Haskell/Liquid/Parse.hs

A workaround for https://github.com/ucsd-progsys/liquidhaskell/issues/854.
This will make the following example work in LH, which I would consider to be good enough™:
```haskell
{-@ LIQUID "--higherorder"        @-}
{-@ LIQUID "--totality"           @-}
{-@ LIQUID "--exactdc" @-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE FlexibleInstances, IncoherentInstances, MultiParamTypeClasses, TypeFamilies #
-}
module Foo where
import Prelude hiding (Either(..))
infixl 3 ==., ?
infixl 2 ***
type Proof = ()
(?) :: (Proof -> a) -> Proof -> a
f ? y = f y
data QED = QED
(***) :: a -> QED -> Proof
_ *** _ = ()
class OptEq a r where
(==.) :: a -> a -> r
instance (a~b) => OptEq a (Proof -> b) where
{- instance OptEq a (Proof -> b) where
==. :: x:a -> y:a -> {v:Proof | x == y} -> {v:b | v ~~ x && v ~~ y} …
```

Allow LH to parse infix datatypes written in prefix form

---

src/Language/Haskell/Liquid/Bare/Plugged.hs

instead use toRSort to strip away the liquid-y bits of the RType,
producing a nice message like
```
/Users/gridaphobe/Source/liquid/haskell/Foo.hs:3:21-50: Error: Specified Type Does Not Refine Haskell Type for Main.propPlusComm
3 | {-@ propPlusComm :: x:Int -> y:Int -> {x+y = y+x} @-}
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
The Liquid type
Int -> Int -> _
is inconsistent with the Haskell type
()
defined at /Users/gridaphobe/Source/liquid/haskell/Foo.hs:5:1-12
```
or
```
/Users/gridaphobe/Source/liquid/haskell/Foo.hs:7:19-33: Error: Specified Type Does Not Refine Haskell Type for Main.impossible
7 | {-@ impossible :: {4 = 5} -> Int @-}
^^^^^^^^^^^^^^^
The Liquid type
_ -> Int
is inconsistent with the Haskell type
forall t a. GHC.Num.Num a => t -> a
defined at …
```

don't use toType while plugging holes

---

src/Language/Haskell/Liquid/Transforms/Rewrite.hs
tests/pos/T866.hs
tests/pos/mapreduce.hs
tests/pos/zipper000.hs
tests/test.hs
tests/todo/mapreduce.hs

Fix for issue #866 
- also, moving `tests/pos/mapreduce.hs` into `tests/todo/` till the undefined issue #862  is fixed.

Fix for issue #866

---

src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Types.hs

spl case monadic-bind ONLY if no abs-refinements

---

TODO.markdown
benchmarks/proofautomation/pos/Ackermann.hs
benchmarks/proofautomation/pos/Append.hs
benchmarks/proofautomation/pos/ApplicativeMaybe.hs
benchmarks/proofautomation/pos/Fibonacci.hs
benchmarks/proofautomation/pos/FoldrUniversal.hs
benchmarks/proofautomation/pos/Maybe.hs
benchmarks/proofautomation/pos/MonoidMaybe.hs
benchmarks/proofautomation/pos/Overview.hs
benchmarks/proofautomation/pos/ProofCombinators.hs
benchmarks/proofautomation/pos/Solver.hs
benchmarks/proofautomation/pos/Unification.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Constraint/Init.hs
src/Language/Haskell/Liquid/Constraint/Instantiate.hs
src/Language/Haskell/Liquid/Constraint/Types.hs
src/Language/Haskell/Liquid/UX/CmdLine.hs
src/Language/Haskell/Liquid/UX/Config.hs
tests/pos/LiquidAutomate.hs
tests/test.hs

Proofs are now done by (in place) evaluation. 
I will formalize and describe the evaluation strategy once all pldi tests pass.

Eval proof strategy

---

README.md

There should perhaps be a link to the tutorial from here too.

Add link to the main web site

---

circle.yml
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/Types.hs
tests/Parser.hs

Left factoring the `forall` and data declaration parsing.

More parser cleanup

---

benchmarks/base-4.5.1.0/Data/List.hs
benchmarks/base-4.5.1.0/GHC/List.lhs
benchmarks/bytestring-0.9.2.1/Data/ByteString.T.hs
benchmarks/bytestring-0.9.2.1/Data/ByteString/Lazy.hs
benchmarks/esop2013-submission/Base.hs
benchmarks/pldi17/pos/Unification.hs
benchmarks/proofautomation/pos/Unification.hs
benchmarks/text-0.11.2.3/Data/Text/Encoding.hs
benchmarks/text-0.11.2.3/Data/Text/Fusion.hs
benchmarks/text-0.11.2.3/Data/Text/Lazy.hs
benchmarks/text-0.11.2.3/Data/Text/Lazy/Fusion.hs
include/GHC/List.spec
src/Language/Haskell/Liquid/Parse.hs
tests/Parser.hs
tests/neg/Strata.hs
tests/pos/IcfpDemo.hs
tests/pos/Infinity.hs
tests/pos/ListMSort-LType.hs
tests/pos/LocalLazy.hs
tests/pos/Repeat.hs
tests/pos/absref-crash.hs
tests/pos/gadtEval.hs
tests/pos/term0.hs

Previously 'Lazy' and 'Strict' were synonyms.
Closes #973

Remove 'Strict' and make 'Lazy' lowercase

---

src/Language/Haskell/Liquid/Parse.hs
tests/Parser.hs

Remove "defined" keyword, it is a synonym for "measure"

---

tests/pos/bar.hs
tests/pos/sf/Basics.hs
tests/pos/sf/Induction.hs

I have partially ported proofs (given or exercises) into Liquid Haskell. The “partial” is to avoid unnecessary repetition.

First two chapters of SF.

---

src/Language/Haskell/Liquid/Constraint/ToFixpoint.hs

bump Fixpoint, fixpoint API

---

README.md
include/Language/Haskell/Liquid/ProofCombinators.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/Types/PredType.hs
src/Language/Haskell/Liquid/Types/RefType.hs
tests/errors/Inconsistent0.hs
tests/neg/Ast.hs
tests/pos/DependentPairs.hs
tests/pos/DependentPairsFun.hs

Syntactic sugar for dependent pairs (without explicitely using Abstract Refinements)

dependent pairs

---

src/Language/Haskell/Liquid/GHC/Interface.hs
tests/pos/T1045.hs
tests/pos/T1045.hs-boot
tests/pos/T1045a.hs

support cyclic modules with hs-boot files

---

benchmarks/bytestring-0.9.2.1/Data/ByteString.T.hs
benchmarks/bytestring-0.9.2.1/Data/ByteString.hs
src/Language/Haskell/Liquid/UX/CmdLine.hs

See NOTE [searchpath] in L.H.L.UX.CmdLine

don't add the directory containing the file to the search path

---

circle.yml

See https://circleci.com/gh/alanz/liquidhaskell/132

Fix Circle CI tests

---

liquidhaskell.cabal

liquidhaskell-0.8.0.3 is released

update fixpoing and versions

---

liquidhaskell.cabal
src/Language/Haskell/Liquid/Types/Errors.hs
src/Language/Haskell/Liquid/UX/Annotate.hs
src/Language/Haskell/Liquid/UX/DiffCheck.hs
stack.yaml

Note: `AnnErrors` seems to be dead code, should it be removed?

Bump aeson version

---

include/Data/Vector/Mutable.spec

This time against develop instead of master. Still WIP.

More vector assumptions
