ucsd-progsys/liquidhaskell

src/Language/Haskell/Liquid/Bare.hs
src/Language/Haskell/Liquid/Errors.hs
src/Language/Haskell/Liquid/Types.hs
tests/crash/RClass.hs

```haskell
module Crash where
class Foo a where
{-@ class Foo where
foo :: x:a -> {v:a | v = x}
@-}
foo :: a -> a       
instance Foo Int where
{-@ instance Foo Int where
foo :: x:Int -> {v:Int | v = x + 1} @-}
foo x = x + 1
instance Foo Integer where
{-@ instance Foo Integer where
foo :: x:Integer -> {v:Integer | v = x + 1} @-}
foo x = x + 1
```
```
tests/crash/RClass.hs:4:11: Error: Refined classes cannot have refined instances
Refined class definition for: Foo
Defined at: tests/crash/RClass.hs:4:11
Refined instance for: Int
Defined at: tests/crash/RClass.hs:11:16
Refined instance for: Integer
Defined at: tests/crash/RClass.hs:16:16
```
vs
```
tests/crash/RClass.hs:4:11: Error: You cannot refine instances of refined classes Foo
```

Improve error for refined class/instances conflict

---

tests/pos/AVLRJ.hs

I added a predicate that strengthens the postconditions on `insert` so, to satisfy the totality checker, we don't need the case checks I removed.
I feel like the type on line 21 shouldn't be required somehow, since by the definition of `balanced`, the absolute value of `bFac` for an `AVLTree` must be 0 or 1.
Probably related to that, the following type checks:
force :: Tree a -> Tree a
{-@ force :: forall <p :: Tree a -> Prop>. t:AVLTree a<p> -> {v:AVLTree a<p> | bFac v <= 1 && bFac v >= -1} @-}
force t@(Nil) = t
force t@(Tree v l r) = t
while this does not:
force :: Tree a -> Tree a
{-@ force :: forall <p :: Tree a -> Prop>. t:AVLTree a<p> -> {v:AVLTree a<p> | bFac v <= 1 && bFac v >= -1} @-}
force t = t
I guess this is because on the constructors Branch and Nil, `balanced` is expanded …

Strengthened the AVL insert function to remove unnecessary guards

---

include/GHC/Num.spec

I don't know why this was commented out but it fixes the issue of having to write `(0-1)` everywhere in code instead of `-1`.
This is faster than fixing it at the CoreToLogic level. Were there some kind of problems with the spec?

Uncommented GHC.Num.negate spec

---

src/Language/Haskell/Liquid/Bare/Expand.hs
src/Language/Haskell/Liquid/Bare/RTEnv.hs
src/Language/Haskell/Liquid/Bare/RefToLogic.hs
src/Language/Haskell/Liquid/Bare/Resolve.hs
src/Language/Haskell/Liquid/CoreToLogic.hs
src/Language/Haskell/Liquid/Types.hs
tests/pos/AVLRJ.hs

LH wasn't able to lift functions with expressions containing `(-1)` into measures (see `tests/pos/AVLRJ.hs` for an example), so I added a type constructor `ENeg` to represent this to `Liquid.Fixpoint.Types.Expr`. See ucsd-progsys/liquid-fixpoint#50

Added ENeg type

---

.travis.yml

It's a hassle to have to make a temporary commit to have Travis build each new development branch. Why not get rid of this whitelist entirely and build all branches on push?

Remove Travis branch whitelist

---

src/Language/Haskell/Liquid/Bare/Env.hs
src/Language/Haskell/Liquid/Bare/OfType.hs
src/Language/Haskell/Liquid/Bare/Resolve.hs
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/Types.hs

We do name resolution on `Expr`s inside `UReft`s, but not in `RExprArg`s in the `RType`s.

Resolve Exprs in RExprArgs

---

.travis.yml

I've been communicating with Travis-CI support, trying to work out the issue we're having with `cabal install` randomly erroring out during builds. They're not sure what the problem is, but they recommend using the standard Travis's standard copies of GHC and Cabal instead of installing our own, to eliminate that as a possible source.
It looks like we're currently using a modified version of [hvr/multi-ghc-travis](https://github.com/hvr/multi-ghc-travis), but it doesn't look like we need to anymore. We're not currently testing against multiple versions of GHC, and [Travis supports that natively now](http://docs.travis-ci.com/user/languages/haskell/) anyway.

Use Travis's standard copy of GHC 7.8 instead of installing our own

---

.travis.yml
scripts/travis

Random network failures during Cabal dependency installs break Travis builds. Work around this by adding travis_retry to commands that install dependencies.
See #362.

Work around Travis issues with travis_retry

---

.travis.yml
scripts/travis
tests/test.hs

@nikivazou and I were discussing this earlier today. When a test fails on Travis, right now, we have to re-run it on our own systems to see log output. Besides being inconvenient, sometimes we have test failures on Travis that we can't reproduce ourselves. This PR modifies the test and Travis scripts to dump the logs of failed tests when running on Travis. It also tightens a few things up in the Travis script.
You can view an example here:
https://travis-ci.org/spinda/liquidhaskell/jobs/57744542#L832-L836
with this at the end:
```
(...)
The command "scripts/travis do_test "$TESTS" "$SMT" && scripts/travis test_source_pkg" exited with 1.
$ scripts/travis dump_fail_logs
./benchmarks/bytestring-0.9.2.1/Data/ByteString/Lazy/.liquid/Char8.hs.log.fail:
http://sprunge.us/FQeJ …
```

Dump logs of failed tests when running on Travis

---

.travis.yml
scripts/travis

Travis has two build systems: a VM-based system and a [Linux containers-based system](http://docs.travis-ci.com/user/workers/container-based-infrastructure/). The latter can run your builds if you don't need `sudo` support. It's much faster to start up and run builds, it has more memory available, it's stabler, and it allows the caching of files between builds. This is the biggest win for us, as caching our Cabal dependencies instead of recompiling them every time cuts total build time in half ([before](https://travis-ci.org/ucsd-progsys/liquidhaskell/builds/57073862) / [after](https://travis-ci.org/spinda/liquidhaskell/builds/59090800)).
Travis can install `apt` packages before removing privileges from your container, as long as they're on a …

Use Travis containers for stabler and 2x faster builds

---

src/Language/Haskell/Liquid/Parse.hs

Just a small change but it seems to fix the issue of paring refined data definitions. #399

Changed reading space to reading blanks in dataDeclFullP

---

tests/test.hs

re: #407
This should work for both `cabal test` and `stack test`.

Determine liquid path relative to test runner

---

src/Language/Haskell/Liquid/GhcInterface.hs

This squelches the
Warning: Couldn't do create temp directory: .liquid: createDirectory: already exists (File exists)
message that shows up sometimes.

Use createDirectoryIfMissing for .liquid dirs

---

include/GHC/Base.spec
include/GHC/CString.spec
src/Language/Haskell/Liquid/ANFTransform.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/CoreToLogic.hs
src/Language/Haskell/Liquid/Literals.hs
src/Language/Haskell/Liquid/Measure.hs
tests/pos/StringLit.hs

add special rule for string literals

---

tests/test.hs

Test suite previously respected the LIQUIDHASKELL_OPTS environment variable, which could cause test failures for seemingly "no reason"
Since you have to explicitly tell the test suite command line arguments via `--liquid-opts`, I feel that it should ignore the environment variable.

Updated tests to ignore LIQUIDHASKELL_OPTS

---

Liquid.hs
src/Language/Haskell/Liquid/CmdLine.hs
src/Language/Haskell/Liquid/Types.hs

Implements supporting config option passing for implementing a maximum partition size limit in fixpoint.
Depends on Fixpoint pull request [#107](https://github.com/ucsd-progsys/liquid-fixpoint/pull/107)

Implement maxpartsize option

---

Liquid.hs
src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Errors.hs
src/Language/Haskell/Liquid/GhcInterface.hs
src/Language/Haskell/Liquid/Literals.hs
src/Language/Haskell/Liquid/Server.hs
src/Language/Haskell/Liquid/WiredIn.hs
tests/pos/ResolvePred.hs

Earlier, given things like:
```
data L a = N | C a (L a)
```
were adding just things like `N` but not the `C` -- deferring the latter to `binds`. In general *all* symbols that appear as applications inside refinements *must* be declared as constants. See #443. 
This particular PR should fix that, by adding all first-order data-constructors.

Add First-Order Data Constructors as Fixpoint Constants

---

src/Language/Haskell/Liquid/CmdLine.hs
src/Language/Haskell/Liquid/Types.hs

Supporting changes in liquidhaskell for making parallel solving the default in fixpoint.
Also contains minor refactoring of defaultFoo functions (factored out into fixpoint where applicable)

Set parallel solving be be default

---

.gitignore
.gitmodules
README.md
stack.yaml

@ranjitjhala, @gridaphobe, @christetreault, and I discussed this today. This sets up `liquid-fixpoint` as a submodule of `liquidhaskell`, and updates the `stack.yaml` file to build from that local copy. (For Cabal users, the sandbox instructions on the README have been updated.)
The process of updating and keeping track of the `liquid-fixpoint` submodule has been documented in the README (under the section "Working With Submodules").
Besides forcing us to keep track of which version of `liquid-fixpoint` we're building against, this lets @christetreault's performance dashboard tie the data it collects to a specific `liquid-fixpoint` commit.

Use a submodule for liquid-fixpoint

---

.gitignore
.gitmodules
.travis.yml
README.md
liquidhaskell.cabal
scripts/travis
stack.yaml

This reworks the Travis build setup to use `stack` for installing GHC, installing dependencies,, and building `liquidhaskell`. This lets us test with multiple GHC versions without relying on either Travis's official GHC support or `multi-ghc-travis`, meaning we can switch back to Travis's Docker system for our builds. That means our builds will run much, much quicker, as (a) the Docker containers take much less time to provision than the full VMs we're currently using, and (b) with the Docker system, we can cache our GHC install and built dependencies across runs, instead of having to rebuild them every single test.
(Note&mdash;this depends on #476 being merged first.)

Use stack and Docker to run tests on Travis

---

scripts/performance/cleanup-gipeda.bash
scripts/performance/deploy-gipeda.bash
scripts/performance/generate-site.bash

Fixes 2 issues:
* Previously attempted to use pwd to determine the current directory. It turns out that pwd only works of you executed: `./generate-site.bash` to start the site generation. Since our cron jobs don't do this, switched to dirname to get the working directory.
* Aborted runs leave a bunch of garbage in the repository. Git seems to think this means I made a bunch of changes that I might want to commit, and helpfully doesn't checkout until I commit or stash. Now, we reset and checkout the repository and submodules prior to trying to work.

Bug fixes for perf-monitor

---

include/GHC/Real.spec

The `quot` and `rem` functions have fewer refinements than `quotRem` and the `divMod` function has fewer refinements than `div`/`mod` so this change makes them behave more consistently

Consistency for `Integral` method refinements

---

src/Language/Haskell/Liquid/Bare/GhcSpec.hs
tests/crash/Assume1.hs

assumed and spec signatures should be treated the same. 
make assumed sigs go though `replaceLocalBinds`

fix for #569

---

scripts/travis
src/Language/Haskell/Liquid/Constraint/Qualifier.hs
src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/UX/CmdLine.hs
src/Language/Haskell/Liquid/UX/Config.hs

Partially fixes #576 by allowing users to override the defaults and scrape qualifiers from imported modules. It's off by default because of the performance implications (I've seen up to 2x overhead on some modules, eg `Data.Text`).

add --scrape-imports to enable scraping qualifiers from imports

---

src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/Types/Errors.hs

This is good, because no we can actually use it everywhere without creating dependency cycles.

L.H.L.Types.Errors no longer imports any LiquidHaskell module

---

README.md

CircleCI seems to be working well, so should we switch the "Build Status" badge from Travis to this?

Switch "Build Status" badge to CircleCI

---

stack.yaml

Currently the stack.yaml plan is using nightly-2016-01-06 which builds against GHC-7.10.3.
Using a LTS resolver allows liquidhaskell to be built inside a Docker container, which may impact reproductibility of builds in a multiple developers environment.
FP Complete provides Docker base images for all their LTS releases, but not for their nightlies.
The most approximate LTS release for `nightly-2016-01-06` is `lts-4.0`, with only two packages differing a version, as it can be seen in the stackage diff at https://www.stackage.org/diff/nightly-2016-01-06/lts-4.0
Namely, the packages are:
- sbv-5.8 (on lts-4.0 it is sbv-5.9)
- web-routes-wai-0.24.2 (on lts-4.0 it is web-routes-wai-0.24.3)
So I wonder whether the resolver can be changed.

Use LTS resolver instead of nightly

---

include/Data/Vector.spec
include/GHC/Types.spec
src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/Types/PrettyPrint.hs
src/Language/Haskell/Liquid/Types/RefType.hs
tests/neg/Variance1.hs
tests/pos/Words.hs
tests/pos/Words1.hs

Fix for #638.
To compute variance we need to take into account the variance of the type constructors that appear in type definitions.
Before, we assumed all type constructors used in the definitions were covariant.

fix for #638

---

include/Data/Vector.spec

Liquid Haskell fails if you use the `Data.Vector` module due to the unqualified reference in `Data/Vector.spec` and succeeds after this change.

Qualify `Vector` type in `Data/Vector.spec`

---

src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Misc.hs
src/Language/Haskell/Liquid/Types.hs
tests/crash/HigherOrder.hs
tests/neg/HigherOrder.hs

When higher order flag is not on, specs that use function symbols crash, [tests/crash/HigherOrder.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/352e7969905cc56ecd555ad5d55037a095a06327/tests/crash/HigherOrder.hs) 
When flag is on the above test is just UNSAFE 
[tests/neg/HigherOrder.hs](https://github.com/ucsd-progsys/liquidhaskell/blob/352e7969905cc56ecd555ad5d55037a095a06327/tests/neg/HigherOrder.hs)

Allow functions only when flag is on

---

src/Language/Haskell/Liquid/Model.hs
src/Language/Haskell/Liquid/Types/RefType.hs
src/Test/Target/Monad.hs
tests/neg/Class1.hs

- use class constraints to drive monomorphization
- default unconstrained `(t :: *)` to `Int`
- default unconstrained `(t :: * -> *)` to `[]`

smarter monomorphization in model-generation

---

benchmarks/bytestring-0.9.2.1/Data/ByteString/Internal.hs
benchmarks/text-0.11.2.3/Data/Text/Array.hs
benchmarks/text-0.11.2.3/Data/Text/Encoding.hs
benchmarks/text-0.11.2.3/Data/Text/Lazy/Encoding.hs
benchmarks/vector-0.10.0.1/Data/Vector/Fusion/Stream/Monadic.hs
benchmarks/vector-0.10.0.1/Data/Vector/Fusion/Stream/Monadic.nocpp.hs
liquidhaskell.cabal
src/Language/Haskell/Liquid/GHC/Interface.hs
src/Language/Haskell/Liquid/Liquid.hs
src/Language/Haskell/Liquid/Misc.hs
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/Types/Errors.hs
src/Language/Haskell/Liquid/UX/Annotate.hs
src/Language/Haskell/Liquid/UX/CmdLine.hs
src/Test/Target/Util.hs
tests/crash/BadPragma0.hs
tests/crash/BadPragma1.hs
tests/crash/BadPragma2.hs
tests/pos/Class2.hs
tests/pos/CommentedOut.hs
tests/pos/FFI.hs
tests/test.hs

This (a) reworks the GHC Interface pipeline to handle multiple target files at once and parse/load each module one-by-one with a dependency graph, and (b) uses that infrastructure to pull comments out of GHC's ApiAnnotations interface instead of using our own parsing for that (fixes #617).
(a) lays the groundwork for the addition of quasiquoters (coming very soon!), .lqhi files, and the GHC plugin interface. It also means LH compiles each module exactly once, which helps a lot with `liquidhaskell-cabal`.
One caveat: this isn't compatible with using `--idirs` inside `{-@ LIQUID @-}` file pragmas. I think the test suite is the only user of this functionality; to make it work, I moved those flags into an `extraOptions` map in the test runner itself.

ApiAnnotations

---

include/Data/ByteString.spec
include/Data/ByteString/Unsafe.spec

The first one is obvious, but I'm particularly unsure about 31733db.
This was found in the process of using `liquidhaskell` on `binary-serialise-cbor`.

Fixes to ByteString specs

---

src/Language/Haskell/Liquid/Constraint/Env.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Constraint/Monad.hs
src/Language/Haskell/Liquid/Constraint/Split.hs
tests/todo/T765.hs

Matching PR for 
https://github.com/ucsd-progsys/liquid-fixpoint/pull/256
**Pruning LH "derived" vars should really be in LH and not in fixpoint.**

No inst constants

---

src/Language/Haskell/Liquid/Bare/Axiom.hs
src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Spec.hs
src/Language/Haskell/Liquid/Constraint/Axioms.hs
src/Language/Haskell/Liquid/Constraint/Env.hs
src/Language/Haskell/Liquid/Constraint/Fresh.hs
src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Constraint/Init.hs
src/Language/Haskell/Liquid/Constraint/Qualifier.hs
src/Language/Haskell/Liquid/Constraint/ToFixpoint.hs
src/Language/Haskell/Liquid/Constraint/Types.hs
src/Language/Haskell/Liquid/GHC/Interface.hs
src/Language/Haskell/Liquid/Liquid.hs
src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/UX/CmdLine.hs
src/Language/Haskell/Liquid/UX/DiffCheck.hs
src/Test/Target/Monad.hs
tests/TestCommits.hs
tests/todo/Incr.hs
tests/todo/Refl.hs
tests/todo/ReflImp.hs

Some tidying up, towards making the code slightly less impenetrable.
* Rename fields of `GhcSpec` so they are prefixed by `gs` -- to facilitate easy search of where they get values,
* Move some stuff out of the gigantic `Constraint.Generate` into `Constraint.Fresh` and a new `Constraint.Init`.
**Please update ASAP if you are working on develop**

Refactor fields

---

src/Language/Haskell/Liquid/Transforms/ANF.hs
tests/tmp/Class2.hs
tests/tmp/Class3.hs
tests/tmp/LiquidR.hs
tests/tmp/Mode.hs
tests/tmp/T776.hs
tests/tmp/T777.hs
tests/todo/T791.hs

Minor change that ensures that ANF variables have distinct ids, 
to make understanding the `Core` easier. 
[LOG](https://github.com/ucsd-progsys/liquid-logger/blob/master/logs/logs-rename-prefix/out/out.csv)

Rename ANF Suffix

---

README.md
src/Language/Haskell/Liquid/Parse.hs
tests/pos/T819.hs

Infix operators can be defined in the logic using a Haskell like notation
{-@ infixl 9 <> @-}
Addresses issue #819

Infix Operators in the logic

---

src/Language/Haskell/Liquid/Bare/Env.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Bare/Spec.hs
src/Language/Haskell/Liquid/Measure.hs
src/Language/Haskell/Liquid/Parse.hs
tests/pos/NatClass.hs

With define we can replace Haskell variables with symbols during constrain. generation 
eg, in the following example
https://github.com/ucsd-progsys/liquidhaskell/pull/867/commits/0123b4081cad10df96ee23f6cc621766b32c8cdc#diff-6e20e8531df8072c56366fdfad9b6c4fR48
```
{-@ define $ceq = eqN @-}
```
replaces the internal class method `$ceq` with `eqN`. 
I am not supplying documentation yet, as this is a temporal solution.

add local defines

---

README.md
benchmarks/base-4.5.1.0/GHC/IO/Encoding/Iconv.hs

I've noticed "Haskell" misspelled in readme. The same error exists in one of the benchmarks. Trailing spaces was removed by my editor(it's better without them anyways :P).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ucsd-progsys/liquidhaskell/874)

misspelled "haskell"

---

INSTALL.md

This pull request updates installation guide when using `cabal` to ensure that the correct GHC version is in the environment. Without this, `cabal install liquidhaskell` with GHC 8 will try to install liquidhaskell-0.4.x.x which does not has an upper bound on GHC's version (and will fail to compile).
The user might not realize that `cabal install` is trying an old version due to dependency problem.
```
$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 8.0.1
$ cabal install liquidhaskell --dry-run
Resolving dependencies...
In order, the following would be installed (use -v for more details):
... [skipped] ...
liquid-fixpoint-0.3.0.1 (latest: 0.5.0.1)
liquidhaskell-0.4.1.1 (latest: 0.6.0.0)
```

Add cabal install instruction to check GHC version

---

benchmarks/pldi17/pos/FoldrUniversal.hs
benchmarks/pldi17/pos/Solver.hs
benchmarks/pldi17/pos/Unification.hs
src/Language/Haskell/Liquid/Constraint/Qualifier.hs
src/Language/Haskell/Liquid/Liquid.hs
src/Language/Haskell/Liquid/UX/CmdLine.hs
tests/pos/mapreduce.hs

Because you can get cyclic dependencies due to polymorphic instantiation, see:
https://github.com/iu-parfunc/verified-instances/blob/master/examples/Peano.hs
where the last trivial proof "instantiating" the Iso is killed if we "--eliminate=all" due to the cycle
induced by
```
data Iso a b = Iso { to   :: a -> b, from :: b -> a ... }
```
Not clear what the best solution here is; really need the qualifiers to solve the above out to `Nat`. 
Hence, am reverting to making `--eliminate=all` be *explicit* (not implied by `--higherorder`).

Make "--eliminate=all" explicit (not default)

---

benchmarks/pldi17/neg/Ackermann.hs
benchmarks/pldi17/neg/ApplicativeList.hs
benchmarks/pldi17/neg/ApplicativeMaybe.hs
benchmarks/pldi17/neg/FunctorList.hs
benchmarks/pldi17/neg/FunctorMaybe.hs
benchmarks/pldi17/neg/MapFusion.hs
benchmarks/pldi17/neg/MonadReader.hs
benchmarks/pldi17/pos/Ackermann.hs
benchmarks/pldi17/pos/ApplicativeId.hs
benchmarks/pldi17/pos/ApplicativeMaybe.hs
benchmarks/pldi17/pos/FoldrUniversal.hs
benchmarks/pldi17/pos/FunctorId.hs
benchmarks/pldi17/pos/FunctorList.hs
benchmarks/pldi17/pos/FunctorMaybe.hs
benchmarks/pldi17/pos/FunctorReader.NoExtensionality.hs
benchmarks/pldi17/pos/FunctorReader.hs
benchmarks/pldi17/pos/MapFusion.hs
docs/blog/2017-01-06-reductions.lhs
docs/blog/todo/Iso.lhs
src/Language/Haskell/Liquid/Bare/Axiom.hs
src/Language/Haskell/Liquid/Bare/GhcSpec.hs
src/Language/Haskell/Liquid/Constraint/Axioms.hs
src/Language/Haskell/Liquid/Constraint/Qualifier.hs
src/Language/Haskell/Liquid/Constraint/ToFixpoint.hs
src/Language/Haskell/Liquid/Measure.hs
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/Types.hs
tests/neg/Automate.hs
tests/pos/Automate.hs

See tests/pos|neg/Automate.hs for axiomatization of the fib function. 
Surprisingly, SMT proving `fibA 30 == 832040` is faster than running `fibA 30` in Haskell! 
I suggest 
- rename all current axiomatize to reflect 
- use the current reflect to build further fuel strategies etc?

Smt axiomatization

---

benchmarks/pldi17/pos/MapFusion.hs
src/Language/Haskell/Liquid/Constraint/ToFixpoint.hs
src/Test/Target/Serialize.hs

Adding a trigger to only instantiate axioms when the left hand side of the axioms equality is ground.
This trigger does not diverge when the compose axiom exists, which made most of our pldi example diverge!
Currently all axiomatized functions use the default (LeftHandSide) trigger https://github.com/ucsd-progsys/liquidhaskell/blob/10178fd99f89fce9e8822ae666a19bbe307d1a1f/src/Language/Haskell/Liquid/Constraint/ToFixpoint.hs#L50.
Since all axiomatized functions terminate this trigger should not diverge, but who knows...

triggering interface

---

liquidhaskell.cabal
tests/test.hs

1. Limit the compiler to GHC 7.10.*
2. Add missing bounds on aeson
3. Use optparse-applicative-0.13 in the tests.
The 3rd can be done alternately by adding an upper bound of
optparse-applicative < 0.13, in which case the new semigroups dependancy and
change to test.hs are not needed.

Ensure installation via cabal

---

stack.yaml

This will transparently add upper and lower bounds to all package dependencies not currently having them, based on the snapshot in use, when the package is uploaded via either stack upload or stack sdist.

Enable Hackage-friendly stack.yaml setting

---

TODO.markdown
benchmarks/pldi17/pos/ApplicativeList.hs
benchmarks/proofautomation/pos/AlphaEquivalence.hs
benchmarks/proofautomation/pos/ApplicativeId.hs
benchmarks/proofautomation/pos/ApplicativeList.hs
benchmarks/proofautomation/pos/FunctorId.hs
benchmarks/proofautomation/pos/FunctorList.hs
benchmarks/proofautomation/pos/FunctorMaybe.hs
benchmarks/proofautomation/pos/MonadList.hs
benchmarks/proofautomation/pos/MonoidList.hs
src/Language/Haskell/Liquid/Constraint/Instantiate.hs
tests/test.hs

- Cleaning symbolic evaluation implementation 
- All (but reader) pldi tests pass
- Only **1** function requires function unfolding. [ApplicativeList.composition](https://github.com/ucsd-progsys/liquidhaskell/compare/eval-proof-strategy?expand=1#diff-0b8ea56a0aba51464e4ea63ae64b0c96R86) because I am not closed under congruence.

Eval proof strategy

---

liquidhaskell.cabal
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/Types.hs
tests/Parser.hs

I anticipate this is an easy to merge PR. This adds a simple test suite that you can run like this:
```
bash-3.2$ stack test :liquidhaskell-parser
liquidhaskell-0.7.0.0: test (suite: liquidhaskell-parser)
Should succeed
Int
k:Int -> Int
Should fail
Maybe k:Int -> Int
Finished in 0.0048 seconds
3 examples, 0 failures
```
I spent most of my energy on trying to get Eq or Show instances for the `Pspec` and related types, but gave up. So I just put in three cases. The Show instance for Psec is now derived. If you want the debugging one, it's still there commented out. 
When you discover a new case (that should or shouldn't work), you just run this in the REPL
```haskell
> parseSingleSpec "a :: {x:Int|x>0} -> ()"
Right "Asrts ([\"a\" defined from: \"<test input>\" (line 1, column 1) to: \"<test …
```

Add trivial parser test suite

---

circle.yml

1. GHC 7.10.3
If a fresh circleci build is started (no cache) the available ghc is
8.0.1, and the machine config does not seem to do anything.
Explicitly install ghc-7.10.3, and configure the build to use it.
2. tasty junit output
For some reason, the --xml file to capture the junit.xml output has to
exist before the tests run, otherwise it crashes with an error related
to canonicalizePath. Create this file before running the tests.

Tweaking circle.yml

---

circle.yml
src/Language/Haskell/Liquid/Bare/OfType.hs
src/Language/Haskell/Liquid/Parse.hs
tests/Parser.hs
tests/test.hs

Finally, use the parsec ability to generate reaonable error messages.
To start with I just put the name of the production in the `<?>` tags, these can be changed to something more useful over time.
Also, we now get the actual error message, rather than just a location and "leftover when parsing".

[WIP don't merge] Improve error messages

---

docs/blog/2016-09-18-refinement-reflection.lhs

Corrects some typos in example code/text snippets referring to code.

Correct some typos in Refinement Reflection blog post

---

src/Language/Haskell/Liquid/GHC/Misc.hs

Now that we have super parse errors (thanks again @alanz!), am tweaking the error location reporting to play better with editor modes.

Add a single column to error location

---

liquidhaskell.cabal

Doing so makes Hackage link directly to the changelog, and renders the README in the Hackage description of the library.

Add CHANGES.md and README.md to extra-source-files

---

.gitignore
cabal.project

`liquiddesugar` is no longer a submodule, yet it was still listed in `cabal.project`, which confuses `cabal new-build`.
While I was in town, I added some build artifacts produced by `cabal new-build`.

Make cabal new-build possible with liquidhaskell

---

include/Data/ByteString.spec
include/Data/ByteString/Lazy.spec
include/Data/ByteString/Short.spec
include/Data/String.spec

Fixes #822
Based on @nikivazou's suggestion
This refines the output of `fromString` to add a new `stringlen` measure
and then adds invariants to the various `ByteString` types to
synchronize this measure with their existing length measures
Testing this also identified some refined types for functions which no
longer exist in more recent versions of the `bytestring` package, so I
removed from the specification files

Add support for `Data.String.fromString`

---

benchmarks/proofautomation/pos/ApplicativeId.hs
benchmarks/sf/Induction.hs
benchmarks/sf/Lists.hs
src/Language/Haskell/Liquid/Bare.hs
src/Language/Haskell/Liquid/Bare/Axiom.hs
src/Language/Haskell/Liquid/Bare/DataType.hs
src/Language/Haskell/Liquid/Bare/Env.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Bare/Misc.hs
src/Language/Haskell/Liquid/Transforms/CoreToLogic.hs
src/Language/Haskell/Liquid/Types.hs
tests/neg/EvalQuery.hs
tests/pos/EvalQuery.hs
tests/pos/T1074.hs
tests/pos/VerifiedMonoid.hs

A lot of the measure instantiation stuff is not needed when using ADTs.
This PR ensures selectors and tests are the same as those used for ADT fields, 
and then eliminates a bunch of the code corresponding to the selectors and test measures.
Matching PR for https://github.com/ucsd-progsys/liquid-fixpoint/pull/325

Simplify PLE (Instantiate) with ADTs

---

src/Language/Haskell/Liquid/Bare/Misc.hs
src/Language/Haskell/Liquid/UX/Errors.hs
src/Language/Haskell/Liquid/UX/Tidy.hs

Simplify errors like 
```
53 |   ==!  C x (N ++ N)
^^^^^^^^^^^^
Inferred type
VV : {v : (L a) | ListExample.size v == 1 + ListExample.size ?g
&& (is$ListExample.N v <=> false)
&& lqdc##select v == ?g
&& lqdc##select v == x
&& lqdc##select v == ?g
&& lqdc##select v == x
&& (is$ListExample.C v <=> true)
&& v == ListExample.C x ?g
&& v == ListExample.C x ?g
&& ListExample.size v >= 0
&& v == ?f
&& ListExample.size v >= 0}
not a subtype of Required type
VV : {VV : (L a) | VV == ?c}
In Context
?g : {?g : (L a) | ?g == ListExample.++ ?a ?e
&& ?g == (if is$ListExample.C ?a then ListExample.C (lqdc##select ?a) (ListExample.++ (lqdc##select ?a) ?e) else ?e)
&& ?g == ListExample.++ ?a ?e
&& ListExample.size ?g >= 0}
xs : {v : (L a) | ListExample.size v >= 0}
?f : {?f : (L a) | ListExample.size ?f …
```

Tidy reflection error messages

---

src/Language/Haskell/Liquid/Constraint/Generate.hs
src/Language/Haskell/Liquid/Constraint/Init.hs
tests/theorem_proving/T1106.hs
tests/theorem_proving/T1106Defs.hs

Before this edit we could not prove the below theorem (see [here](https://github.com/ucsd-progsys/liquidhaskell/blob/42fa24a8a2ace7b6464007b8b13da5f77769a046/tests/theorem_proving/T1106.hs)) when `foo` is imported. 
```
mapFoo (foo c) (Foo b) = Foo (foo c b)
```
The reason? The type of `foo c` is true while it should be `{v: a -> b | v == foo c}`
When higher-order flag is on two kinds of functions were given singleton/functional types (like `v == foo c`)
- local fuctional variable (as stored in `fargs γ`)
- reflected functions (as stored in `aenv γ`)
The problem: imported reflected functions are not added in `aenv`
This branch solves this problem by giving singleton functional types to all function applications, when the HO flag is on. 
But, travis rejects this solution since it can give …

imported reflected HO functions

---

src/Language/Haskell/Liquid/Liquid.hs
src/Language/Haskell/Liquid/UX/CmdLine.hs

So that the descriptions don't get wrapped into teeny narrow columns.
PS: sorry for the this being so hacky, the `CmdArgs` library doesn't allow tweaking the format of its generated help menu...
Before:
After:

Wide Help 

---

TODO.md
benchmarks/popl18/ple/pos/Fibonacci.hs
src/Language/Haskell/Liquid/Bare.hs
src/Language/Haskell/Liquid/Bare/Check.hs
src/Language/Haskell/Liquid/Bare/DataType.hs
src/Language/Haskell/Liquid/Bare/Lookup.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Measure.hs
src/Language/Haskell/Liquid/Types.hs
tests/import/lib/T1112.hs
tests/import/lib/T1112Lib.hs

When checking a module `Client` with `--exact-data-con`, 
automatically "lift" or "reflect" all the `TyCon`s that are used 
in *reflected* functions inside `Client`, _even_ when the `Library` 
defining the `TyCon` does not use `--exact-data-con` 
(or is generally unavailable for analysis.)
Fixes #1112 
See the above issue for a use case.
Of course, we cannot lift some primitive `TyCon` like `Bool` and tuples.

Lift Imported TyCons

---

src/Language/Haskell/Liquid/Bare.hs
src/Language/Haskell/Liquid/Bare/DataType.hs
src/Language/Haskell/Liquid/Bare/Measure.hs
src/Language/Haskell/Liquid/Bare/Spec.hs
src/Language/Haskell/Liquid/Parse.hs
src/Language/Haskell/Liquid/Types.hs
src/Language/Haskell/Liquid/Types/PredType.hs
src/Language/Haskell/Liquid/WiredIn.hs
tests/import/lib/T1117.hs
tests/import/lib/T1117Lib.hs
tests/import/lib/T1118.hs
tests/import/lib/T1118Lib1.hs
tests/import/lib/T1118Lib2.hs

Fixes #1117 
We can end up with multiple data-declarations if we automatically reflect data types (as in `--exact-data-con` / ADT mode.) 
Consequently, we need to "resolve" the definitions to get a SINGLE definition. 
See the `[NOTE:Orphan-TyCons]` in `Bare/DataType.hs` for details.

Resolve Multiple Data-declarations 
